version: '3'
services:
  weather-etl:
    image: y0ndu/weather-etl
    volumes: 
      - "./credentials.json:/app/credentials.json"
      - "./.env:/app/.env"
      - "./profiles.yml:/app/profiles.yml"